# -*- coding: utf-8 -*-
"""CSE221_LAB2_Task-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S0VUma2hUkK9kUNTEf80f_4qBCZA31NI
"""

file_input=open("/content/Input3.txt","r")
file_output=open("/content/Output3.txt","w")
x=int(file_input.readline())
arr=[]
def tasks(task_break):
  task_break.sort(key=lambda interval: interval[1])

  tasks_not_overlapped=[]
  last_task_end_time=0

  for task_interval in task_break:
    task_start_time,task_end_time=task_interval
    if task_start_time>=last_task_end_time:
      tasks_not_overlapped.append(task_interval)
      last_task_end_time=task_end_time

  return tasks_not_overlapped

for i in range(x):
  arr1=file_input.readline().split()
  start=int(arr1[0])
  end=int(arr1[1])
  arr.append((start,end))
completed_tasks=tasks(arr)
file_output.write(str(len(completed_tasks))+"\n")
for arr in completed_tasks:
  file_output.write(f"{arr[0]} {arr[1]}\n")


file_input.close()
file_output.close()