# -*- coding: utf-8 -*-
"""CSE221LAB2Task-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CSqFnV8QieWsBsiBZNzj9pFd1qr2_tVI
"""

###Task-1(a)

file_input=open("/content/Input1(a).txt","r")
file_output=open("/content/Output1(a).txt","w")
x,y=(file_input.readline().strip().split(' '))
z=map(int,file_input.readline().split(" "))
list_1=list(z)
sum=" "


for i in range(len(list_1)):
  for j in range(i+1,len(list_1)):
    if int(list_1[i])+int(list_1[j])==int(y):
      sum=(str(i+1)+" " + str(j+1))
      file_output.write(sum)
      break





file_input.close()
file_output.close()