# -*- coding: utf-8 -*-
"""LAB04_Task01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FcLPn8BMB14Zed1sNSrOElVMaR6oUXQo
"""

#Task-1(a)

with open("/content/Input1(a).txt", "r") as input_file:
    N, M = map(int, input_file.readline().split())  ##N=Node,M=edges
    adjacency_matrix = [[0] * (N + 1) for _ in range(N + 1)]

    for _ in range(M):
        edge = input_file.readline().split()
        ui = int(edge[0])   ##Starting node
        vi = int(edge[1])    ##Ending node
        wi = int(edge[2])    ##Weight
        adjacency_matrix[ui][vi] = wi
for row in adjacency_matrix[1:]:
    for i in range(1, N + 1):
        print(row[i], end=' ')
    print()
with open("/content/Output1(a).txt", "w") as output_file:
    for row in adjacency_matrix[1:]:
        for i in range(1, N + 1):
            output_file.write(str(row[i]) + " ")
        output_file.write("\n")