# -*- coding: utf-8 -*-
"""Task_1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UxRG2_PYsyC-oY098pwJayAxRAvcH1qn
"""

with open("/content/Input1(b).txt", "r") as file:
    input_values = file.readline().split()
    N = int(input_values[0])
    M = int(input_values[1])
    adjacency_list = {}

    for i in range(N + 1):
        adjacency_list[i] = []

    for _ in range(M):
        edge = file.readline().split()
        ui = int(edge[0])
        vi = int(edge[1])
        wi = int(edge[2])
        adjacency_list[ui].append((vi, wi))
for vertex, edges in adjacency_list.items():
    print(vertex, end=" : ")
    if edges:
        for i, edge in enumerate(edges):
            print("({}, {})".format(edge[0], edge[1]), end="")
            if i != len(edges) - 1:
                print(" ", end="")
    print()
with open("/content/Output1(b).txt", "r") as output_file:
    output_lines = output_file.readlines()