# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xrkedb8VZSCaae7Y-uNqh6lbIolW4AM7
"""

def find_max(a, b):
    if type(a) == int and type(b) == int:
        return max(a, b)

    sorted_arr = []
    i = 0
    j = 0
    max_value = 0

    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            max_value = max(max_value, b[j])
            j += 1
        else:
            max_value = max(max_value, a[i])
            i += 1

    while i < len(a):
        max_value = max(max_value, a[i])
        i += 1

    while j < len(b):
        max_value = max(max_value, b[j])
        j += 1

    return max_value

def find_max_sorted(arr):
    if len(arr) <= 1:
        return arr[0] if arr else float('-inf')
    else:
        mid = len(arr) // 2
        left_max = find_max_sorted(arr[:mid])
        right_max = find_max_sorted(arr[mid:])
        return find_max(left_max, right_max)

input_file = open("/content/Input2.txt", "r")
output_file = open("/content/Output2.txt", "w")

n = input_file.readline()
s = input_file.readline().strip()
lst = list(map(int, s.split(" ")))

max_value = find_max_sorted(lst)
output_file.write(f"{max_value}")

input_file.close()
output_file.close()