# -*- coding: utf-8 -*-
"""Task-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XNVxegm7dHo_N1wi9rrrZD68ifvGwX87
"""

import sys
def find_ij_max(array, size):
    max_i = (-sys.maxsize - 1, 0)
    max_j = (-sys.maxsize - 1, 0)
    index = 1

    for k in range(size - 1):
        if array[k] < 0:
            if abs(array[k]) >= max_j[0]:
                if max_j[0] > max_i[0]:
                    max_i = max_j
                max_j = (array[k], k)
                index = k
        elif array[k] > max_j[0] or array[k] > max_i[0]:
            if array[k] > max_j[0]:
                if max_j[0] > max_i[0]:
                    max_i = max_j
                max_j = (array[k], k)
                index = k
            elif array[k] > max_i[0] and k != index:
                max_i = (array[k], k)

    if max_i[1] > max_j[1]:
        result = max_j[0] + max_i[0] ** 2
    else:
        result = max_i[0] + max_j[0] ** 2

    return result

input_file = open('/content/Input4.txt', 'r')
output_file = open('/content/Output4.txt', 'w')
n = int(input_file.readline().strip())
arr = list(map(int, input_file.readline().split()))
output_file.write(f'{find_ij_max(arr, n)}')
input_file.close()
output_file.close()