# -*- coding: utf-8 -*-
"""Task-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H9GEn7phInjPia6yvljm0v_XMxyXK85u
"""

def partition(array, low, high):
    pivot = array[high]
    i = low - 1
    for j in range(low, high):
        if array[j] <= pivot:
            i = i + 1
            array[i], array[j] = array[j], array[i]
    array[i + 1], array[high] = array[high], array[i + 1]
    return i + 1

def quick_sort(array, low, high):
    if low < high:
        partition_index = partition(array, low, high)
        quick_sort(array, low, partition_index - 1)
        quick_sort(array, partition_index + 1, high)

input_file = open('/content/Input5.txt', 'r')
output_file = open('/content/Output5.txt', 'w')
n = int(input_file.readline())
arr = list(map(int, input_file.readline().split(' ')))
quick_sort(arr, 0, n - 1)
for i in arr:
    output_file.write(str(i) + ' ')
input_file.close()
output_file.close()