# -*- coding: utf-8 -*-
"""Task-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16KjkQ_IneHhdeCqPOwWKfHDcLCvjgBCa
"""

def merge(left, right):
    sorted_arr = []
    i = 0
    j = 0
    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            sorted_arr.append(left[i])
            i += 1
        else:
            sorted_arr.append(right[j])
            j += 1

    while i < len(left):
        sorted_arr.append(left[i])
        i += 1

    while j < len(right):
        sorted_arr.append(right[j])
        j += 1

    return sorted_arr

def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr) // 2
        left = mergeSort(arr[:mid])
        right = mergeSort(arr[mid:])
        return merge(left, right)

input_file = open('/content/Input1.txt', 'r')
output_file = open('/content/Output.txt', 'w')
n = input_file.readline()
numbers = input_file.readline()
arr = numbers.split(" ")
res = [eval(i) for i in arr]

final = mergeSort(res)
for item in final:
    output_file.write(f'{item} ')
input_file.close()
output_file.close()